version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
    - .:/opt/app
    env_file:
      - .env
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db

volumes:
  pg_data: {}
  pg_backups: {}
