# Generated by Django 2.0.3 on 2018-03-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('accounts', '0001_squashed_0003_auto_20180203_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.ManyToManyField(to='goals.Goal'),
        ),
    ]
